pipeline{
  agent any

  stages{
    stage('build'){
      steps{
        sh '''
        echo "Build Stage is successful"
        '''
      }
    }
    stage('deploy'){
      steps{
        sh '''
          echo "App deployed"
          '''
      }
    }      
  }
  }
