pipeline{
  agent any

  stages{
    stage('build'){
      steps{
        sh '''
            echo "Build stage is successful."
        '''
      }
    }

    stage('deploy'){
      steps{
        sh '''
            echo "App deployed"
        '''
      }
    }
  }
}
